import { cp, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const projectDirectory = new URL("../", import.meta.url);
const sourceDirectory = new URL("../src/", import.meta.url);
const publicDirectory = new URL("../public/", import.meta.url);
const legacyOutputDirectory = new URL("../dist/", import.meta.url);

// The project root is the unpacked extension directory. Keep source folders
// intact and remove only files/directories generated by this script.
for (const directory of ["background", "content", "popup", "options", "icons", "styles"]) {
  await rm(new URL(`../${directory}/`, import.meta.url), { recursive: true, force: true });
}
await rm(new URL("../manifest.json", import.meta.url), { force: true });
await cp(publicDirectory, projectDirectory, { recursive: true });

await build({
  absWorkingDir: fileURLToPath(new URL("../", import.meta.url)),
  bundle: true,
  entryPoints: [
    fileURLToPath(new URL("background/index.ts", sourceDirectory)),
    fileURLToPath(new URL("content/index.ts", sourceDirectory)),
    fileURLToPath(new URL("content/main-world-bridge.ts", sourceDirectory)),
    fileURLToPath(new URL("popup/index.ts", sourceDirectory)),
    fileURLToPath(new URL("options/index.ts", sourceDirectory)),
  ],
  format: "iife",
  outbase: "src",
  outdir: fileURLToPath(projectDirectory),
  platform: "browser",
  sourcemap: true,
  target: "chrome121",
});

// Remove the old duplicate output after a successful root build.
await rm(legacyOutputDirectory, { recursive: true, force: true });
